import Link from "next/link";

import { Page } from "@/components/shell/app-shell";
import { Timeline } from "@/components/journey/timeline";
import { Button } from "@/components/ui/button";
import { EmptyState, Separator, Surface } from "@/components/ui/surface";
import { dayNumber, daysBetween, formatDay, today } from "@/lib/dates";
import { queryIndex } from "@/lib/storage/index-store";
import { getOrCreateJourney } from "@/lib/storage/journey";
import { preparationProgress } from "@/lib/analytics/compute";
import { PlannerReport } from "@/components/ai/reports";
import { isAiConfigured } from "@/lib/env";

/**
 * Journey Home.
 *
 * Answers the four questions from the spec — where am I, what have I done,
 * what matters now, what next — and then stops. The first viewport stays
 * deliberately quiet: no statistics grid, no dashboard.
 */
export default async function HomePage() {
  const journey = await getOrCreateJourney();
  const { entries, total } = await queryIndex({ limit: 5 });
  const progress = await preparationProgress();
  const aiConfigured = isAiConfigured();

  const now = today();
  const day = dayNumber(journey.startDate, now);
  const daysLeft = journey.targetDate
    ? daysBetween(now, journey.targetDate)
    : null;

  return (
    <Page width="reading">
      <header>
        <p className="text-meta text-ink-muted">
          Day {day} · started {formatDay(journey.startDate)}
        </p>

        <h1 className="text-page text-ink mt-1 font-medium tracking-tight">
          {journey.title}
        </h1>

        <p className="text-ink-secondary mt-2">{journey.target}</p>

        {daysLeft !== null ? (
          <p className="text-meta text-ink-muted mt-3">
            {daysLeft > 0
              ? `${daysLeft} days to ${formatDay(journey.targetDate!)}`
              : daysLeft === 0
                ? "Target date is today"
                : `Target date passed ${Math.abs(daysLeft)} days ago`}
          </p>
        ) : null}
      </header>

      {journey.currentFocus ? (
        <section className="mt-section">
          <h2 className="text-meta text-ink-muted">Current focus</h2>
          <p className="text-ink mt-1">{journey.currentFocus}</p>
        </section>
      ) : null}

      {/*
        Today's plan is generated by the AI planner in Phase 5. Until then the
        slot states plainly that it is empty rather than pretending otherwise.
      */}
      <section className="mt-section">
        <h2 className="text-meta text-ink-muted">Tomorrow</h2>
        <Surface className="mt-2">
          {aiConfigured ? (
            <PlannerReport />
          ) : (
            <p className="text-small text-ink-muted">
              Decide the one thing that matters tomorrow and write it down
              tonight. With a Gemini key configured, the planner can suggest it
              from what you actually did today.
            </p>
          )}
        </Surface>
      </section>

      <Separator className="my-section" />

      {/*
        The one figure Home is allowed. The spec is explicit that the first
        screen must not become a dashboard, so this is a sentence with a number
        in it rather than a chart, and it links to the page that has the rest.
      */}
      {progress.entries > 0 ? (
        <p className="text-small text-ink-muted mb-section">
          You have recorded something on {progress.activeDays} of{" "}
          {progress.dayNumber} days.{" "}
          <Link
            href="/analytics"
            className="text-accent underline underline-offset-4"
          >
            See the rest
          </Link>
          .
        </p>
      ) : null}

      <section>
        <div className="mb-4 flex items-baseline justify-between gap-3">
          <h2 className="text-meta text-ink-muted">Recent journey</h2>
          {total > entries.length ? (
            <Link
              href="/journey/timeline"
              className="text-meta text-accent underline-offset-4 hover:underline"
            >
              All {total} entries
            </Link>
          ) : null}
        </div>

        {entries.length === 0 ? (
          <EmptyState
            title="Nothing recorded yet"
            description="Mark the day you started, and the journey has a beginning."
            action={
              <Link href="/journey/milestones">
                <Button variant="primary">Add a milestone</Button>
              </Link>
            }
          />
        ) : (
          <Timeline entries={entries} />
        )}
      </section>
    </Page>
  );
}
