import fsp from "node:fs/promises";
import { PassThrough } from "node:stream";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore -- archiver 8 ships no typings, and the published @types package
// still describes the v5 callable API that this version replaced.
import { ZipArchive } from "archiver";

import { today } from "@/lib/dates";
import { getOrCreateJourney } from "@/lib/storage/journey";
import { DATA_ROOT, UPLOADS_ROOT } from "@/lib/storage/paths";
import { getIndex } from "@/lib/storage/index-store";

/**
 * Export the whole journey as a zip.
 *
 * The journal is the user's, and it should be possible to walk away with it.
 * Everything inside is already plain Markdown, JSON and WebP, so the archive
 * is readable with nothing but a file browser — no import step, no database,
 * no version of this app required.
 *
 * A README is written into the archive explaining the layout, because an
 * export a stranger cannot read is not really a backup.
 */

/**
 * The slice of archiver this route uses.
 *
 * Declared here because archiver 8 ships no types of its own and the community
 * `@types/archiver` package still describes the v5 callable API, which this
 * version replaced with classes. A wrong shape here type-checks cleanly and
 * throws at runtime, so `tests/export.test.ts` opens a real archive.
 *
 * In v8 each format is its own class taking only options — `new ZipArchive({…})`,
 * not `archiver("zip", {…})` and not `new Archiver("zip", {…})`, both of which
 * construct an object with no format module attached.
 */
interface Zip {
  on(event: "warning" | "error", handler: (error: Error) => void): void;
  pipe(destination: NodeJS.WritableStream): void;
  append(source: string, options: { name: string }): void;
  directory(source: string, destination: string): void;
  finalize(): Promise<void>;
}

async function exists(target: string): Promise<boolean> {
  try {
    await fsp.access(target);
    return true;
  } catch {
    return false;
  }
}

function readme(journey: { title: string; startDate: string }, count: number) {
  return `# ${journey.title}

Exported ${today()} — ${count} entries, journey started ${journey.startDate}.

Everything here is plain text or standard image files. You do not need the
application that produced it.

## Layout

    journey.json        Title, start date, target, current focus.
    index.json          A cache: one lightweight record per entry. Rebuildable
                        from the files below, so it can be ignored or deleted.
    diary/              One Markdown file per day, named YYYY-MM-DD.md.
    reflections/        Longer reflections.
    experiences/        Life events recorded alongside the preparation.
    letters/            "Dear Future Me" letters. Some have an openOn date in
                        their front matter; those were written to be read later.
    milestones/         Moments worth marking, as JSON.
    problems/           The problem journal: attempts, struggles, breakthroughs.
    topics/             Notes on DSA topics. Counts are derived, not stored.
    notes/              Learning notes.
    fundamentals/       CS fundamentals notes.
    designs/            System design records.
    sessions/           Practice sittings.
    interviews/         Mock interview transcripts.
    bookmarks.json      Ids that were starred.
    uploads/            Images referenced from entries, as /uploads/... paths.

## Reading a Markdown entry

Each file starts with a YAML front matter block between \`---\` lines holding
the metadata, followed by the entry itself. The text below the second \`---\`
is exactly what was written, unaltered.

Any \`aiReflection\` block in the front matter was generated by an assistant
and accepted by the author. It is kept separate from the body on purpose: the
words below the front matter are always the author's own.
`;
}

export async function GET(): Promise<Response> {
  try {
    const [journey, index] = await Promise.all([
      getOrCreateJourney(),
      getIndex(),
    ]);

    const archive: Zip = new ZipArchive({ zlib: { level: 9 } });
    const passthrough = new PassThrough();

    archive.on("warning", (error) => console.warn("[export]", error));
    archive.on("error", (error) => {
      console.error("[export]", error);
      passthrough.destroy(error);
    });

    archive.pipe(passthrough);

    archive.append(readme(journey, index.length), {
      name: "journey-export/README.md",
    });

    if (await exists(DATA_ROOT)) {
      archive.directory(DATA_ROOT, "journey-export");
    }
    if (await exists(UPLOADS_ROOT)) {
      archive.directory(UPLOADS_ROOT, "journey-export/uploads");
    }

    // Not awaited: finalize resolves once the archive is fully written, and
    // the response streams while that happens.
    void archive.finalize();

    const filename = `journey-export-${today()}.zip`;

    return new Response(passthrough as unknown as ReadableStream, {
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="${filename}"`,
        "Cache-Control": "no-store",
      },
    });
  } catch (error) {
    console.error("[export]", error);
    return new Response(
      "Couldn't build the export. Your journal is unaffected.",
      { status: 500 },
    );
  }
}

export const dynamic = "force-dynamic";
